### ISSUE TITLE
Problem mit Mensaplan

### ISSUE THREAD

**Issue by DATBOIWASHERE** [gymh/android#18]
Mensa plan kann nicht geöffnet werden - Problem bereits bekannt

Biete Hilfe an

**Comment by philippdormann** [comment]
Hallo "DATBOIWASHERE",

der Parser für MensaMax ist seit längerem defekt. s wird aktuell an einer Lösung gearbeitet, sodass der Speiseplan demnächst wieder zur Verfügung stehen wird.
Den entsprechenden Issue findest du hier: https://github.com/philippdormann/gymhmensa/issues/10
