### ISSUE TITLE
Bug - News verschwinden im Darkmode

### ISSUE THREAD

**Issue by Missin-No** [gymh/android#19]
![Screenshot_20210629_072608_de philippdormann gymnasiumherzogenaurach](https://user-images.githubusercontent.com/86645595/123742369-ce795f00-d8ab-11eb-8d6d-b3f4f27dc0a0.jpg)

**Comment by nicolaiort** [comment]
Kann reproduziert werden, danke für den Hinweis :)

**Comment by philippdormann** [comment]
Danke, ist behoben ✅
